### ISSUE TITLE
Не отрабатывает ip 'last' -dp 'ael'

### ISSUE THREAD

**Issue by wolfktl** [Dragonim/1C8InstallAndUninstall#3]
При выборе ip 'last' -dp 'ael' ставит поселению версию платформу, а предыдущее не удаляет

**Comment by wolfktl** [comment]
Не работает ael
В логах:
Параметры запуска скрипта: -dd '\\MSK-03\1CDistr' -dl 'C:\scripts\1Clogs' -dp 'ael' -ip 'no' -iod 'DESIGNERALLCLIENTS=0 THINCLIENT=1 THINCLIENTFILE=0'
2019.10.24 17:31:53 Начало работы скрипта
2019.10.24 17:32:03 Окончание работы скрипта

**Comment by Dragonim** [comment]
Какой-то странный у вас путь к папке с дистрибутивами "\MSK-03\1CDistr". Может быть в начале должно быть два слеша, т.е. "\\MSK-03\1CDistr"

А так же надо помнить что параметр "ael" удаляет только те платформы, которые имеются в папке с дистрибутивами.
