### ISSUE TITLE
Переданный скрипту параметр "-iod" имеет не допустимое значение "DESIGNERALLCLIENTS=1

### ISSUE THREAD

**Issue by iacsvrn** [Dragonim/1C8InstallAndUninstall#4]
powershell "\\x.x.x.x\1CDistr\1C8InstallAndUninstall.ps1" -dd '\\x.x.x.x\1CDistr' -dl '\\x.x.x.x\1CDistr\1CLog' -ip 'last' -dp 'ael' -iod 'DESIGNERALLCLIENTS=1 THINCLIENT=1 THINCLIENTFILE=0'

2020.01.09 19:25:05 Переданный скрипту параметр "-iod" имеет не допустимое значение "DESIGNERALLCLIENTS=1". Будут установлены все клиентские компоненты платформы.

Версия 1С: 8.3.15.1830

**Comment by Dragonim** [comment]
Судя по логу вы передаете параметру -iod значение "DESIGNERALLCLIENTS=1", а скрипт ожидает 'DESIGNERALLCLIENTS=1 THINCLIENT=1 THINCLIENTFILE=0' в котором можно менять 1 на ноль и обратно.
