### ISSUE TITLE
Прекращается работа скрипта, вызванная перезагрузкой во время установки скриптом

### ISSUE THREAD

**Issue by iacsvrn** [Dragonim/1C8InstallAndUninstall#5]
Запускаю скрипт с ключами.
Ставит vc_redist.x64
Перезагрузка
==
Всё. скрипт видит последнюю версию 1C. Но она не установена.
При запуске 1С говорит, что возможно после перезагрузки будет установлена новая версия
Перезагрука -> ничего не меняется. версия прежняя. и новую не устанавливает.

===
Версии ПО:

> Microsoft Windows [Version 10.0.17763.914]
> Версия 1С: 8.3.15.1830

===

в логах:

> 2020.01.09 19:30:58 Начало работы скрипта
> 2020.01.09 19:31:33 Последняя (старшая) платформа 8.3.15.1830 уже установлена.
> 2020.01.09 19:31:33 Окончание работы скрипта

**Comment by Dragonim** [comment]
Добавил /norestart при установки vc_redist. Не факт что это поможет избежать перезагрузки при установки, т.к. такого ключа нет в справке, но будем надеется и верить. Так же переместил часть с подготовкой инсталятора перед непосредственной установкой.

Ваша проблема в том что подготовка к установки уже произошла, а потому система считает что сама установка тоже произошла. На данном компьютере лучше произвести установку вручную.
